"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { API, Document, Message, Project, Result, request } from "../lib/api";

export default function Workspace({ project }: { project: Project }) {
 const [documents,setDocuments]=useState<Document[]>([]),[results,setResults]=useState<Result[]>([]),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("");
 const load=async()=>{setDocuments(await request(`/api/projects/${project.id}/documents`));setResults(await request(`/api/projects/${project.id}/results`));setMessages(await request(`/api/projects/${project.id}/chat/history`));};
 useEffect(()=>{load();const events=new EventSource(`${API}/api/projects/${project.id}/events`);events.onmessage=load;events.addEventListener("document.status",load);events.addEventListener("job.completed",load);return()=>events.close()},[project.id]);
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);await fetch(`${API}/api/projects/${project.id}/documents`,{method:"POST",body:form});await load();}
 async function send(e:FormEvent){e.preventDefault();if(!text.trim()||busy)return;const question=text;setText("");setBusy(true);setStatus("Retrieving grounded context…");setMessages(m=>[...m,{role:"user",content:question},{role:"assistant",content:""}]);const response=await fetch(`${API}/api/projects/${project.id}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:question})});const reader=response.body?.getReader();const decoder=new TextDecoder();let buffer="";while(reader){const next=await reader.read();if(next.done)break;buffer+=decoder.decode(next.value,{stream:true});const parts=buffer.split("\n\n");buffer=parts.pop()||"";for(const part of parts){const event=part.match(/^event: (.+)$/m)?.[1],data=part.match(/^data: (.+)$/m)?.[1];if(!event||!data)continue;const value=JSON.parse(data);if(event==="token"){setStatus("");setMessages(m=>m.map((item,i)=>i===m.length-1?{...item,content:item.content+value.text}:item))}if(event==="done"){setMessages(m=>m.map((item,i)=>i===m.length-1?{...item,citations:value.citations}:item));if(value.artifact)load()}if(event==="error")setStatus(value.message)}}setBusy(false)}
 return <main className="shell"><aside className="panel"><Link href="/" className="brand">Docuwing</Link><b>{project.name}</b><label className="upload">＋ Upload document<input type="file" hidden onChange={upload}/></label>{documents.map(d=><div className="item" key={d.id}>{d.filename}<div className="status">{d.status}</div></div>)}</aside><section className="main"><div className="header">Ask your documents</div><div className="messages">{messages.length?messages.map((m,i)=><article className={`message ${m.role}`} key={i}><div className="meta">{m.role === "user" ? "You" : "Docuwing"}</div>{m.content || (busy ? "Thinking…" : "")}{m.citations?.length?<div className="status">Sources: {m.citations.map(c=>c.label).join(", ")}</div>:null}</article>):<p className="empty">Upload a document and ask a grounded question. Ask for a report to create a versioned Markdown result.</p>}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about this project…"/><button disabled={busy}>{busy?"Working…":"Send"}</button></form>{status?<div className="status">{status}</div>:null}</section><aside className="panel right"><b>Results</b>{results.map(r=><div className="item" key={r.id}><a href={`${API}/api/results/${r.id}/versions/1/export`}>{r.title}</a><div className="status">{r.kind}</div></div>)}</aside></main>
}
