from pathlib import Path
from uuid import uuid4
import aiofiles
from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import get_settings
from app.core.errors import NotFoundError, ValidationError
from app.db.session import get_session
from app.models import Document, Job, Project
from app.schemas.api import DocumentOut
from app.services.events import event_bus

router = APIRouter(prefix="/api", tags=["documents"])
ALLOWED = {".pdf", ".docx", ".pptx", ".xlsx", ".txt", ".md", ".csv", ".png", ".jpg", ".jpeg"}

@router.post("/projects/{project_id}/documents", response_model=DocumentOut, status_code=202)
async def upload(project_id: str, file: UploadFile = File(...), session: AsyncSession = Depends(get_session)):
    if not await session.get(Project, project_id): raise NotFoundError("Project not found")
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in ALLOWED: raise ValidationError("Unsupported document type")
    settings = get_settings(); token = str(uuid4()); path = settings.storage_root / "projects" / project_id / "documents" / "raw" / f"{token}{suffix}"; path.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    async with aiofiles.open(path, "wb") as target:
        while chunk := await file.read(1024 * 1024):
            total += len(chunk)
            if total > settings.max_upload_mb * 1024 * 1024: path.unlink(missing_ok=True); raise ValidationError("File exceeds upload size limit")
            await target.write(chunk)
    document = Document(project_id=project_id, filename=Path(file.filename or "document").name, mime_type=file.content_type or "application/octet-stream", storage_path=str(path)); session.add(document); await session.flush()
    job = Job(project_id=project_id, job_type="ingest", payload={"document_id": document.id}); session.add(job); await session.commit(); await session.refresh(document)
    await event_bus.publish(project_id, "document.status", {"document_id": document.id, "status": "queued", "job_id": job.id})
    return document

@router.get("/documents/{document_id}", response_model=DocumentOut)
async def get_document(document_id: str, session: AsyncSession = Depends(get_session)):
    document = await session.get(Document, document_id)
    if not document: raise NotFoundError("Document not found")
    return document

@router.get("/documents/{document_id}/content")
async def document_content(document_id: str, session: AsyncSession = Depends(get_session)):
    document = await session.get(Document, document_id)
    if not document: raise NotFoundError("Document not found")
    # Stored paths are generated by this service, never accepted from the client.
    root = get_settings().storage_root.resolve(); path = Path(document.storage_path).resolve()
    if root not in path.parents or not path.is_file(): raise NotFoundError("Document content not found")
    return FileResponse(path, media_type=document.mime_type, filename=document.filename)

@router.delete("/documents/{document_id}", status_code=204)
async def delete_document(document_id: str, session: AsyncSession = Depends(get_session)):
    document = await session.get(Document, document_id)
    if not document: raise NotFoundError("Document not found")
    Path(document.storage_path).unlink(missing_ok=True); await session.delete(document); await session.commit()
